CREATE TABLE "common_code" (
	"code_group_cd" varchar(100) NOT NULL,
	"code_cd" varchar(100) NOT NULL,
	"code_label" varchar(100) NOT NULL,
	"code_description" text,
	"sort_order" integer NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_sys" varchar(50) DEFAULT 'pdfowers' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar(100) DEFAULT 'system' NOT NULL,
	"updated_sys" varchar(50) DEFAULT 'pdfowers' NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" varchar(100) DEFAULT 'system' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "common_code_code_group_cd_code_cd_pk" PRIMARY KEY("code_group_cd","code_cd")
);
--> statement-breakpoint
INSERT INTO "common_code" ("code_group_cd", "code_cd", "code_label", "code_description", "sort_order", "is_active", "created_by", "updated_by") VALUES
	('USER_STATUS', 'active', '활성', '정상 사용 가능한 사용자 계정 상태', 10, true, 'system-seed', 'system-seed'),
	('USER_STATUS', 'merged', '통합됨', '다른 대표 계정으로 통합된 보조 계정 상태', 20, true, 'system-seed', 'system-seed'),
	('AUTH_PROVIDER', 'kakao', '카카오', '카카오 간편로그인 제공자', 10, true, 'system-seed', 'system-seed'),
	('AUTH_PROVIDER', 'naver', '네이버', '네이버 간편로그인 제공자', 20, true, 'system-seed', 'system-seed'),
	('AUTH_PROVIDER', 'google', '구글', '구글 간편로그인 제공자', 30, true, 'system-seed', 'system-seed'),
	('MERGE_STATUS', 'pending', '대기', '계정 통합 요청이 승인 전인 상태', 10, true, 'system-seed', 'system-seed'),
	('MERGE_STATUS', 'approved', '승인', '계정 통합 요청이 승인된 상태', 20, true, 'system-seed', 'system-seed'),
	('MERGE_STATUS', 'cancelled', '취소', '계정 통합 요청이 취소된 상태', 30, true, 'system-seed', 'system-seed'),
	('MERGE_STATUS', 'expired', '만료', '계정 통합 요청이 만료된 상태', 40, true, 'system-seed', 'system-seed'),
	('JOB_STATUS', 'pending', '대기', '후속 작업이 실행 전인 상태', 10, true, 'system-seed', 'system-seed'),
	('JOB_STATUS', 'running', '실행중', '후속 작업이 실행 중인 상태', 20, true, 'system-seed', 'system-seed'),
	('JOB_STATUS', 'completed', '완료', '후속 작업이 정상 완료된 상태', 30, true, 'system-seed', 'system-seed'),
	('JOB_STATUS', 'failed', '실패', '후속 작업이 실패한 상태', 40, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'LOCAL_USER_CREATED', '로컬 계정 생성', 'ID/PW 기반 사용자 생성 이벤트', 10, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'LOGIN_SUCCESS', '로그인 성공', '인증 성공 이벤트', 20, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'LOGIN_FAILURE', '로그인 실패', '인증 실패 이벤트', 30, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'AUTH_IDENTITY_LINKED', '인증수단 연결', 'OAuth 식별자 연결 이벤트', 40, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'AUTH_IDENTITY_UNLINKED', '인증수단 해제', 'OAuth 식별자 해제 이벤트', 50, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'ACCOUNT_MERGE_REQUESTED', '계정 통합 요청', '계정 통합 요청 생성 이벤트', 60, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'ACCOUNT_MERGE_APPROVED', '계정 통합 승인', '계정 통합 승인 이벤트', 70, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'ACCOUNT_MERGE_CANCELLED', '계정 통합 취소', '계정 통합 요청 취소 이벤트', 80, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'ACCOUNT_MERGE_EXPIRED', '계정 통합 만료', '계정 통합 요청 만료 이벤트', 90, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'ACCOUNT_MERGED', '계정 통합됨', '보조 계정이 대표 계정으로 통합된 이벤트', 100, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'EMAIL_VERIFICATION_REQUIRED', '이메일 인증 필요', '이메일 인증 필수 설정에 의해 로그인이 제한된 이벤트', 110, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'VERIFIED_EMAIL_DELETED', '인증 이메일 삭제', '검증 이메일 삭제 이벤트', 120, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'EMAIL_CHANGE_REQUESTED', '이메일 변경 요청', '이메일 변경 요청 이벤트', 130, true, 'system-seed', 'system-seed'),
	('AUDIT_EVENT_TYPE', 'EMAIL_CHANGED', '이메일 변경 완료', '새 이메일 인증 후 이메일이 교체된 이벤트', 140, true, 'system-seed', 'system-seed')
ON CONFLICT ("code_group_cd", "code_cd") DO UPDATE SET
	"code_label" = excluded."code_label",
	"code_description" = excluded."code_description",
	"sort_order" = excluded."sort_order",
	"is_active" = excluded."is_active",
	"updated_at" = now(),
	"updated_by" = 'system-seed',
	"version" = "common_code"."version" + 1;
