export const AUTH_ERRORS = Object.freeze({
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  AUTH_IDENTITY_ALREADY_LINKED: "AUTH_IDENTITY_ALREADY_LINKED",
  ACCOUNT_MERGE_REQUIRED: "ACCOUNT_MERGE_REQUIRED",
  LOCAL_CREDENTIAL_REQUIRED: "LOCAL_CREDENTIAL_REQUIRED",
  EMAIL_VERIFICATION_REQUIRED: "EMAIL_VERIFICATION_REQUIRED"
});
