export const AUTH_ERRORS = Object.freeze({
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  AUTH_IDENTITY_ALREADY_LINKED: "AUTH_IDENTITY_ALREADY_LINKED",
  ACCOUNT_MERGE_REQUIRED: "ACCOUNT_MERGE_REQUIRED",
  LOCAL_CREDENTIAL_REQUIRED: "LOCAL_CREDENTIAL_REQUIRED",
  EMAIL_VERIFICATION_REQUIRED: "EMAIL_VERIFICATION_REQUIRED",
  VERIFIED_EMAIL_REQUIRED: "VERIFIED_EMAIL_REQUIRED",
  AUTH_IDENTITY_NOT_LINKED: "AUTH_IDENTITY_NOT_LINKED",
  MERGE_REQUEST_EXPIRED: "MERGE_REQUEST_EXPIRED",
  MERGE_REQUEST_CANCELLED: "MERGE_REQUEST_CANCELLED",
  MERGE_REQUEST_NOT_PENDING: "MERGE_REQUEST_NOT_PENDING",
  DUPLICATE_MERGE_APPROVAL: "DUPLICATE_MERGE_APPROVAL"
});

export type AuthErrorCode = (typeof AUTH_ERRORS)[keyof typeof AUTH_ERRORS];
